install.packages("vars")
library(vars)
data <- data.frame(Final_Data)
var_model_1 <- VAR(data, p = 2)
summary(var_model_1)
library(xtable)
var_summary_1 <- summary(var_model_1)
var_table_1 <- xtable(var_summary_1$varresult)
library(stargazer)
stargazer(var_model_1, type = "latex")
irf_var_model1 <- irf(var_model_1)
View(irf_var_model1)
print(irf_var_model1)
plot(irf_var_model1)
